repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
      - id: debug-statements

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.4.0
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "-l", "79"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus, --py310-plus, --py311-plus]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python
        args: ["-l 79"]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.1
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-debugger,
            flake8-use-fstring,
          ]
        args:
          [
            "--extend-ignore=S105,E203,W503,E701",
            "--per-file-ignores=__init__.py:F401",
          ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit
        args: ["-c", ".bandit"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        name: mypy
        args: ["--disallow-untyped-defs"]
        additional_dependencies:
          [
            "types-jsonschema",
            "types-tqdm",
            "types-tabulate",
            "scipy-stubs",
            "matplotlib", # There are no official stubs for matplotlib
          ]
        exclude: "^tests/"
